wip
dart-code-checker/dart-code-metrics-action pull request #68
Opened 2021-12-05 18:11 UTC by dkrutskikh

2021-12-05 18:35 UTC, dkrutskikh commented
test

2021-12-06 18:34 UTC, dkrutskikh commented
test comment

2021-12-08 18:24 UTC, incendial requested changes

2021-12-09 20:37 UTC, dkrutskikh commented on action.yml
> +    description: "Publish reports results to GitHub PullRequest review comments."
fixed

2021-12-09 20:38 UTC, dkrutskikh commented on action_app/lib/src/task.dart
> +export async function getPreviousComment(
removed

2021-12-11 12:28 UTC, incendial approved these changes

2021-12-12 06:48 UTC, merged